### ISSUE TITLE
Will you be releasing this on the chrome extension store?

### ISSUE THREAD

**Issue by icantremember** [wseagar/eight-dollars#1]
I'd feel (a bit) safer and it would sync across installs that way.

**Comment by Lifearoundhere** [comment]
Dev response from Twitter
![image](https://user-images.githubusercontent.com/43389663/201168400-34ce5c09-5806-45c2-9bf6-2f7d29c7bb96.png)

**Comment by wseagar** [comment]
> I'd feel (a bit) safer and it would sync across installs that way.
> 
> 

Hi! Yeah it had been submitted to the store for approval. Installing as a dev extension is just temporary until it gets approved 👍

I'll update the readme to let everyone know

**Comment by wseagar** [comment]
Closing because I will track progress in the below issue

https://github.com/wseagar/eight-dollars/issues/12
