### ISSUE TITLE
Turkish language support

### ISSUE THREAD

**Issue by Batuhan445** [wseagar/eight-dollars#10]
It would be nice if it could be added.

Actually verified = Zaten onaylı
Paid for verification = Ödeyerek onaylandı

**Comment by philippemiron** [comment]
You can now manually set the text in the preferences panel with the latest version.

![Screen Shot 2022-11-12 at 15 55 13](https://user-images.githubusercontent.com/387624/201494205-0255eca7-a730-418d-be0d-553092147060.png)

**Comment by wseagar** [comment]
Thanks @philippemiron for answering. Yep will close this since now you can insert your own text in whatever language you choose.
