### ISSUE TITLE
Chrome Web Store

### ISSUE THREAD

**Issue by wseagar** [wseagar/eight-dollars#12]
Issue to track chrome web store submission process.

Current status: Pending

**Comment by infinitepower18** [comment]
It's live now: https://chrome.google.com/webstore/detail/eight-dollars/fjbponfbognnefnmbffcfllkibbbobki

**Comment by wseagar** [comment]
Have submitted v1.2, will close this and update the readme when it's live

**Comment by WilliamDavidHarrison** [comment]
@waltzaround @wseagar It has been updated to v1.2.1

**Comment by waltzaround** [comment]
1.2.1 was a hotfix to fix some issues, 1.3 is pending review atm 🥳
