### ISSUE TITLE
Add-ons for Firefox Store

### ISSUE THREAD

**Issue by wseagar** [wseagar/eight-dollars#13]
Firefox version has been submitted to extension store.

It will appear here when ready https://addons.mozilla.org/en-US/firefox/addon/eightdollars/

Current status: awaiting approval

Signed XPI firefox package is here: https://github.com/wseagar/eight-dollars/releases/download/v1.1/eight-dollars-v1.1-firefox.xpi

**Comment by wseagar** [comment]
Have added installation instructions for firefox on twitter https://twitter.com/willseagar/status/1590850922099666944

**Comment by evilpie** [comment]
Seems like it's available know.

**Comment by wseagar** [comment]
Is available
