### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by tuggernuts** [wseagar/eight-dollars#14]
Just noticed this. A screenshot is best way to explain.

This was in a twitter list. a retweet of an account showed as "paid", but the account is actually verified.
<img width="603" alt="Screen Shot 2022-11-10 at 19 09 44" src="https://user-images.githubusercontent.com/36776999/201232614-49841a43-1d9d-4e15-a12a-47227ffe59fc.png">
Let me know if you need more info...

**Comment by wseagar** [comment]
Thanks for reporting this. I finally figured it out it was a bit of a goof I made when quickly putting this together last night. https://github.com/wseagar/eight-dollars/commit/a1d053706e70e7c62b06ffca040d52a6499d23ba Will go out with v1.2 tomorrow.

**Comment by tuggernuts** [comment]
Great work, by the way. I can only hope Twitter is around long enough for this to have been worth your while. 🙂
