### ISSUE TITLE
[Suggestion] Make the "Paid for verification" Comic Sans

### ISSUE THREAD

**Issue by TheJakeMoore** [wseagar/eight-dollars#17]
I'm not on a machine where I can create the pull request, but I think this change would match type of people who've paid the $8.

**Comment by GeorgeSpelvin** [comment]
👆🏻✔

**Comment by wseagar** [comment]
Let's track options requests in [here](https://github.com/wseagar/eight-dollars/issues/38). We have the ability to turn on/off the comic sans "$" so far but no toggle for the text. Feel free to add a request.
