### ISSUE TITLE
Not seeing extra information in timeline

### ISSUE THREAD

**Issue by lexcyn** [wseagar/eight-dollars#2]
If I browse to the accounts full profile I can see the new badges, but not in the Twitter timeline. Is this supposed to happen or should you see the "actually verified" or "paid for verification" in the timeline for 'verified' accounts? I tested in both Chrome and Edge and see the same.

**Comment by wseagar** [comment]
Is timeline not working for anyone else. I have a bunch of improvements going out with v1.2 which is increasing the reliability across the site. I'll leave this open incase we hear of anyone else with similar issues.

**Comment by SupersSpartan** [comment]
yeah, I don't see it on my timeline, only when I click on a user's profile

**Comment by lexcyn** [comment]
This is fixed in 1.2. Thanks! This extension is great :)
