### ISSUE TITLE
Does not work when the display language is Japanese

### ISSUE THREAD

**Issue by Robot-Inventor** [wseagar/eight-dollars#20]
It doesn't work when the display language is Japanese.
![image](https://user-images.githubusercontent.com/50550561/201246387-854680f8-dc58-4f93-ad71-6cf2e528b9eb.png)

It works well when the display language is English.
![image](https://user-images.githubusercontent.com/50550561/201246499-321d913f-6c46-4abf-86e6-6ea9bdb6764b.png)

**Comment by book000** [comment]
This is a screenshot of the class display in the developer tools when the display language is set to Japanese. Please refer to it.  
The Japanese version of the class name does not have `r-37j5jr`.
https://github.com/wseagar/eight-dollars/blob/a1d053706e70e7c62b06ffca040d52a6499d23ba/script.js#L69-L70

![image](https://user-images.githubusercontent.com/8929706/201316322-87e5674c-00cc-465a-90f6-2e4d152c280c.png)

**Comment by book000** [comment]
In addition, it appears that the `profileNode` also needs to be modified.  
The Japanese version of the tweet class name does not have `r-poiln3`.
https://github.com/wseagar/eight-dollars/blob/a1d053706e70e7c62b06ffca040d52a6499d23ba/script.js#L71-L72

![image](https://user-images.githubusercontent.com/8929706/201318783-e76ec4c9-c805-41b5-af4b-9c4443b8387f.png)

**Comment by book000** [comment]
This problem has not been resolved. See [comment #31](https://github.com/wseagar/eight-dollars/pull/31#issuecomment-1312252554).

**Comment by noway** [comment]
Described a possible solution here: https://github.com/wseagar/eight-dollars/pull/31#issuecomment-1312463192
