### ISSUE TITLE
(Suggestion) make it available on Edge store

### ISSUE THREAD

**Issue by dtantono** [wseagar/eight-dollars#22]
Hi
I know there is a pending progress for Chrome store and it will great to support Edge store as well

**Comment by waltzaround** [comment]
Hey @dtantono - its pending review atm on the edge extension store

**Comment by waltzaround** [comment]
Still waiting...
![Screen Shot 2022-11-15 at 9 12 56 PM](https://user-images.githubusercontent.com/9004833/201865243-51540f30-eea6-4103-bdc0-f2f6ae6a4744.png)

**Comment by infinitepower18** [comment]
In my experience Microsoft is the worst when it comes to extension review times. They took 1 week to approve my extension while all the other stores (Chrome, Firefox, Safari and Opera) took less than 24 hours.

**Comment by andeqdea** [comment]
It's now available in the Edge extensions store
