### ISSUE TITLE
Show the actual verified accounts and twitter blue users status on who to follow

### ISSUE THREAD

**Issue by dtantono** [wseagar/eight-dollars#24]
Hi
it looks good so far. But, I hope we can check the status easily from who to follow column 

![image](https://user-images.githubusercontent.com/29157187/201272043-f22e9a17-4e97-47d6-9bc5-4b9c88e14489.png)

**Comment by wseagar** [comment]
Hi @dtantono, I believe this is working already. Those are verified accounts. You should see the $ icon if they are paid users.

![image](https://user-images.githubusercontent.com/9096644/201314144-662ce9a1-9de7-4be9-9a7e-dc6ff94d6373.png)

If this is still not working for you please feel free to reopen this issue and thanks for posting!

**Comment by dtantono** [comment]
@wseagar understood, So, the blue checkmark means true verified user. Is that so?
