### ISSUE TITLE
manifest is missing/unreadable on ms edge

### ISSUE THREAD

**Issue by aphelionosu** [wseagar/eight-dollars#25]
![image](https://user-images.githubusercontent.com/41836319/201274311-002e9409-2057-44bf-a82a-428d19d6eee4.png)
So uh... this can't be used for edge?

**Comment by zikyfranky** [comment]
I made use of it on Edge

The problem is that you are trying to import the "assets" folder, whereas you are supposed to import THE WHOLE repo folder

@wseagar it would be best if you closed this, as this is a problem caused by the consumer

**Comment by wseagar** [comment]
Thanks for answering @zikyfranky. I haven't tested on edge but I'll take your word for it. @aphelionosu try importing the whole folder as @zikyfranky said. Feel free to reopen this if it's still not working!
