### ISSUE TITLE
Could this extension work on embed tweets?

### ISSUE THREAD

**Issue by panblue** [wseagar/eight-dollars#28]
I don't know how hard (or time-worthy since Musk is going to be doing and undoing a lot of features) it would be to implement this extension to embed tweets. So, I'm asking if it's possible to incorporate this in embedded tweets. Thanks.

**Comment by wseagar** [comment]
Hey, this should be working on embedded tweets already. I believe I found a major bug in my code which was causing it to occasionally fail (generating most of the bug reports here). I'm going to close this and if it's still not working after v1.2 we can revisit it and see if there are any other changes needed. Thank you for raising this!  https://github.com/wseagar/eight-dollars/commit/a1d053706e70e7c62b06ffca040d52a6499d23ba
