### ISSUE TITLE
What is the license for this project?

### ISSUE THREAD

**Issue by Skylled** [wseagar/eight-dollars#3]
Thanks for this fun extension. I'd love to modify it to display things a bit differently, but I don't want to do so without proper license/permission.

What license are you distributing this open source code under?

**Comment by wseagar** [comment]
> Thanks for this fun extension. I'd love to modify it to display things a bit differently, but I don't want to do so without proper license/permission.
> 
> 
> 
> What license are you distributing this open source code under?

Hey! Sorry for not adding a licence yet. I didn't expect so much interest. We will add a licence later today when I have some time. Would you be interested in doing your changes as a PR instead? 

I'll be adding an options panel today too so we can flag some different visual styles off.

**Comment by wseagar** [comment]
Added MIT license ea152b820316bdb02c3145193ed6e35790382274
