### ISSUE TITLE
Option to remove verified mark for twitter blue

### ISSUE THREAD

**Issue by GLedoussal** [wseagar/eight-dollars#30]
I forked the extension to add an option to remove the blue mark for blue subscribers because I prefer to totally ignore them.
I don't know if I should make a PR ?

If anyone else is interested in this option, you can find my commit here : https://github.com/GLedoussal/eight-dollars/commit/1e8e7d9a0231fcf5b7317fb9d094b452d8376df6

**Comment by wseagar** [comment]
Hey @GLedoussal,

Very keen to have this in. Please submit a PR! (Options is not done yet tomorrow we'll be doing some more changes but if you submit the PR before we get up we'll get it in)

**Comment by wseagar** [comment]
Merged. Thanks guys!
