### ISSUE TITLE
Add clown mode 🤡

### ISSUE THREAD

**Issue by Caspy7** [wseagar/eight-dollars#33]
Please include a mode which leaves blue check marks for normal, verified users and for paid users replaces the check mark with 🤡

**Comment by vvirtues** [comment]
How about just custom icons for general use? You can use emojis for defaults, but allow people to set their own icons. Very general

**Comment by wseagar** [comment]
https://github.com/wseagar/eight-dollars/issues/36 Let's do it. Let's track it here!
