### ISSUE TITLE
Twitter has broken the extension.

### ISSUE THREAD

**Issue by LocoCubano** [wseagar/eight-dollars#35]
Update seems to have just been pushed to the  website.

![image](https://user-images.githubusercontent.com/25106883/201370616-1bf5b37a-4274-4d21-9714-3bc4d5bb87ab.png)

The Trump parody account is paid verified while Alex Segura is actual verified. 

Edit: Umm oops... I moved the folder and that's what broke it. OOPS. Closing this,

**Comment by CallMeSlinky** [comment]
They keep changing their styles, they broke my extensions 3 times when making it. I give up until there's something stable. 🤣

**Comment by 4yx** [comment]
The extension I installed yesterday (directly from main) is still working for me.

**Comment by noway** [comment]
@LocoCubano watch the space for the version `1.3` - we re-engineered the way checkmarks are found in the layout and it will be more robust.
