### ISSUE TITLE
[Bug] Showing wrong info

### ISSUE THREAD

**Issue by Ivanraez** [wseagar/eight-dollars#39]
First in my standard notifications tab I see this mixed info, same user and verified because of Twitter blue but on the like notification it shows they are legit.

![image](https://user-images.githubusercontent.com/87554193/201446301-35f82c08-28d0-4413-ab19-0881e86db930.png)

**Comment by Ivanraez** [comment]
And while scrolling through my timeline I found this recommended Tweet shown to me because it got liked by a user I follow and there are 2 issues with this one.

1- Mixed info on the author of the Tweet, they are verified because of Twitter Blue and on the Tweet it shows they are legit but when I hover over their username it shows correct info.

2- At the bottom you can see Tom Brady's account which is the real one but shows he is verified because of Twitter blue tho if I click and go to his profile it does show the proper Verified badge.

![image](https://user-images.githubusercontent.com/87554193/201447614-146fb77a-529b-4e61-a6ff-4e0544fda4fd.png)

**Comment by nin0-dev** [comment]
Or this:
![image](https://user-images.githubusercontent.com/75569739/201474619-aeb610a8-ca08-49b0-ba8f-344b42d6b912.png)

**Comment by noway** [comment]
@Ivanraez @nin0-dev this should be fixed as of `1.3`

**Comment by wseagar** [comment]
Hi @Ivanraez @nin0-dev as Ilia said we believe we've fixed this as of v1.3

We've just added a new bug report template that collects additional info that we need to debug these issues. (Browser extension version, language, region etc).

If this is still an issue after updating could you please reopen this using the template?

**Comment by Ivanraez** [comment]
@wseagar I just updated, all seems good so far, if I see any more bugs I will let you know and thanks for making this extension, very useful!
