### ISSUE TITLE
Port for Firefox? 

### ISSUE THREAD

**Issue by maxxcrawford** [wseagar/eight-dollars#4]
Related issue: #3  

Create a compatible version for Firefox (Manifest v2) 

Context: https://twitter.com/Techman0/status/1590748545904410624#m

**Comment by the-jame** [comment]
🙏

**Comment by helloimbernardo** [comment]
I believe that apart from a couple of manifest file changes the code itself works without alteration as [Firefox should support all chrome.* APIs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension#api_namespace)

I managed to get it to work by implementing [this manifest file for the firefox version](https://github.com/helloimbernardo/eight-dollars/blob/firefox-port/firefox-manifest.json)

**Comment by mazercore** [comment]
When I tried to change the version and load it into Firefox this is the error I received 
`Extension is invalid

Reading manifest: Error processing web_accessible_resources.0: Expected string instead of {"resources":["script.js"],"matches":["https://twitter.com/*","https://mobile.twitter.com/*"]}`

**Comment by helloimbernardo** [comment]
In Manifest V2 the web_accessible_resources tag must recieve an array containing the resources while in Manifest V3 it should be an array of objects [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/web_accessible_resources#manifest_v2_syntax)

**Comment by mazercore** [comment]
@helloimbernardo Great work. Currently its loaded in the temporary position for firefox, right now it displays this: 
>Reading manifest: Warning processing id: An unexpected property was found in the WebExtension manifest.

but otherwise it does work!

**Comment by helloimbernardo** [comment]
I edited my fork to work with Firefox by default and removing that issue (I wrongly assumed I needed to include the ID in the Manifest). [Should work by default :) ](https://github.com/helloimbernardo/eight-dollars/tree/firefox-port)

**Comment by wseagar** [comment]
> I edited my fork to work with Firefox by default and removing that issue (I wrongly assumed I needed to include the ID in the Manifest). [Should work by default :) ](https://github.com/helloimbernardo/eight-dollars/tree/firefox-port)

Hi! Great work, can you please make a PR and I'll get it merged later today and write up instructions/docs?

**Comment by wseagar** [comment]
Thanks to @helloimbernardo for doing the initial work with manifest v2. Closing because we have submitted to the firefox store and a firefox release is on the releases page. We may/may not write manual installation instructions depending on how long firefox takes to approve. The issue below has all the relevant info I will be closing this issue now.

https://github.com/wseagar/eight-dollars/issues/13
