### ISSUE TITLE
[Feature Request] Icon-Only Mode

### ISSUE THREAD

**Issue by MaxJW** [wseagar/eight-dollars#5]
Loving this extension, but I think I prefer it with just the images being switched around, would it be possible to have this as an option somehow?

Referring to removing the following:
* <p style=' font-size: 0.8rem; margin: 0; font-weight: 600;'>Actually Verified</p>
* <p style=' font-size: 0.8rem; margin: 0; font-weight: 600;'>Paid for Verification</p>

Then removing some of the styling in the div containers, I think this looks quite good.
E.g.
Verified:
![image](https://user-images.githubusercontent.com/15789924/201167310-afda63b3-d441-4277-86ed-024c2e99b4b3.png)

Paid:
![image](https://user-images.githubusercontent.com/15789924/201167400-cc4baa71-0629-4c6d-8601-4617b607098e.png)

Love the extension, cheers guys!

**Comment by JonUleis** [comment]
I'm in agreement that iconography is the way to go - the current look adds visual clutter. Plus right now on light mode, only the $8 users have a blue icon, which makes it confusing at a glance.

Here's a proposal that leaves alone actually verified users but quickly helps distinguish the "red flag" $8 users on both light or dark mode.

![image](https://user-images.githubusercontent.com/7644941/201198030-bfb146fd-a9c6-413b-b177-602f8fa3fb64.png)

**Comment by battierp** [comment]
cool extension! i'd like an icon-only mode too or maybe reduced text [paid for verification] = [paid] and [actually verified] = [verified] so it doesn't cut off display names 
![image](https://user-images.githubusercontent.com/50279654/201213198-923217e9-f1b4-497d-8f95-47544f6b75eb.png)

**Comment by wseagar** [comment]
All great bits of feedback.

I'm going to work on getting an options panel working today and we'll then start making all of this configurable. 

I like the more explicit "Actually Verified"/"Paid for Verification" since it is more meme-able and seems to be doing quite well in screenshots but I don't see any reason why we can't make all of this configurable once you have the extension installed.

**Comment by wseagar** [comment]
Hey guys, options/settings panel is in master and is getting close to being able to be released. Going to close this for now and can we track options/feature requests in [here](https://github.com/wseagar/eight-dollars/issues/38)
