### ISSUE TITLE
Stop working when connected to multiple accounts

### ISSUE THREAD

**Issue by lionelpenuchot** [wseagar/eight-dollars#52]
Tested on Edge and Firefox:
If I connect to a single Twitter account then extension works as expected, i.e. displays paid/verified on blue badge accounts.
When I connect to an additional Twitter account then the extension stops displaying the paid/verified status
Disconnecting from one of the accounts is not enough, need to disconnect all Twitter accounts and connect to only one.

**Comment by waltzaround** [comment]
Hmm, mind chucking up some screenshots? Am connected to multiple accounts at this end and it works atm

**Comment by waltzaround** [comment]
Console output might be helpful as well

**Comment by wseagar** [comment]
Hi @lionelpenuchot , sorry we've just added a new bug report template that collects additional info that we need to debug these issues. (Browser extension version, language, region etc).

Could you please reopen this using the template?

**Comment by lionelpenuchot** [comment]
I reenter the bug with the new form, the description is slightly different, as I don't need to connect to a secondary twitter account
see https://github.com/wseagar/eight-dollars/issues/57
