### ISSUE TITLE
Does not work anymore.

### ISSUE THREAD

**Issue by MenschenToaster** [wseagar/eight-dollars#53]
Worked yesterday but today it broke. I'm on Firefox Developer Edition 107.0b9

Could be linked to #52 because I have multiple accounts(but it worked like normal yesterday)

**Comment by wseagar** [comment]
Hi @MenschenToaster, sorry we've just added a new bug report template that collects additional info that we need to debug these issues. (Browser extension version, language, region etc).

Could you please reopen this using the template?
