### ISSUE TITLE
[BUG] Does not work anymore. 

### ISSUE THREAD

**Issue by MenschenToaster** [wseagar/eight-dollars#54]
**Info (please complete the following information):**
 - Browser: Firefox Developer Edition 107.0b9 
 - Platform: Windows 11 Pro 64Bit
 - Extension Version: 1.3
 - Location: Austria [🇦🇹](https://emojipedia.org/de/flagge-%C3%B6sterreich/) (Not Australia!!!)
 - Twitter Language: German

**What happened**
1. Go to 'twitter.com'
3. Scroll down to some user that has blue or is actually verified
4. See the normal twitter checkmark

**Screenshots**
![grafik](https://user-images.githubusercontent.com/54715954/201781930-c36fc758-7990-49f9-bf54-67b2b2898ddf.png)

**Expected behavior**
It should show a custom badge for blue users and show a text for actually verified usrs

**Additional context**
I'm logged into multiple accounts(4)
Browser has been fully restarted before writing this.

May be linked to #52 or the new issue the user might create. At the time of writing this there was no other issue that I could've linked.

**Comment by noway** [comment]
@MenschenToaster can you try setting Display Language to English? The non-English support is still not released

**Comment by MenschenToaster** [comment]
> @MenschenToaster can you try setting Display Language to English? The non-English support is still not released

That seems to be the issue. But why was it working yesterday? Or did my twitter language suddenly change? I don't look at the language the platforms use 😅

**Comment by noway** [comment]
@MenschenToaster we were relying on minified classnames before version `1.3`. That classname version seemed to have been working for German. Twitter pushed an update and changed up their classnames. We had to push `aria-label` based version `1.3` live. But `aria-label` based version only supports English. Non-English support is coming in `1.4` (currently in `main`)

**Comment by MenschenToaster** [comment]
Ah okay. Thanks!

**Comment by steffhelbling** [comment]
Seeing this issue and reading "Non-English support is coming in 1.4 (currently in main)", I briefly tried the WIP 1.4 version and it seems good with my French displayed Twitter.
Nice to see it coming back as I reverted to 1.2 for now.

**Comment by wseagar** [comment]
@MenschenToaster v1.4 has been released do you want to give it a go?

**Comment by MenschenToaster** [comment]
Yes, everything works as expected!
![grafik](https://user-images.githubusercontent.com/54715954/203078941-25ad738e-4b97-47d0-ab82-24a721106ffd.png)
