### ISSUE TITLE
Feat: Remove reliance on specific css selectors

### ISSUE THREAD

**Issue by raed667** [wseagar/eight-dollars#6]
The selectors seem very specific and would break if any class changes or the structure of the dom changes.

https://github.com/wseagar/eight-dollars/blob/main/script.js#L41-L50

Is there any other way we can target these DOM elements?

**Comment by wseagar** [comment]
I'd love some help if you knew how to write some more specific selectors for these elements, that is not really my strong suit 👍

**Comment by wseagar** [comment]
I might be wrong but I think that it's a hard problem since:

1. The css class names are auto generated likely in twitters build process, I think they might change each release

2. This script actually depends on looking into twitters react internals. Any changes to internal component structure on the nodes we're looking at will break this. Better selectors won't make this less fragile.

**Comment by wseagar** [comment]
@raed667 Do you have any suggestions

**Comment by noway** [comment]
@wseagar You can try to start with `$('[aria-label="Verified account"]')` and then walk up and done the node tree to look for the right elements (`headerNode`, `tweets`, `profileNode`, `spaces` would only be fragile).

**Comment by wseagar** [comment]
Have chatted with @noway about this. We have something that kind of works. It's quite hacky. Had to revert the first implementation lets see if we can get it working

**Comment by raed667** [comment]
@wseagar If we're visiting a profile we can listen to `webRequest` to catch the response and have the user object as JSON.

Otherwise with parsing DOM, I like @noway idea.

**Comment by raed667** [comment]
Another idea, create a small cache server where users of the extension share data about profiles once scrapped and then just fetch by twitter-id.

**Comment by noway** [comment]
This one is done as of `v1.3`

**Comment by raed667** [comment]
Great work !!
