### ISSUE TITLE
[BUG] Does not work when in the Notifications Tab

### ISSUE THREAD

**Issue by jaff80** [wseagar/eight-dollars#60]
**Info**
 - Browser: Firefox 107.0 (64-bit)
 - Platform: macOS Ventura 13.0.1
 - Extension Version: 1.3
 - Location: US

**What happened**
1. Go to Notifications
2. Scroll down until you see someone with a checkmark
3. See the error

**Screenshots**
<img width="965" alt="Screenshot 2022-11-19 at 10 39 38 PM" src="https://user-images.githubusercontent.com/113552154/202886148-d7b74f76-38c4-4506-9b18-a9021e6e733d.png">

<img width="965" alt="Screenshot 2022-11-19 at 10 49 18 PM" src="https://user-images.githubusercontent.com/113552154/202886180-a9d9c7c6-8d38-441b-9151-08aab4c80cd6.png">

**Expected behavior**
I should have seen the money badge instead of the real one

**Additional context**
My settings: 
<img width="1329" alt="Screenshot 2022-11-19 at 10 51 50 PM" src="https://user-images.githubusercontent.com/113552154/202886239-b6bb8798-bedc-438d-958d-c280bd457fe6.png">

**Comment by noway** [comment]
@jaff80 Update to `main`, this has been fixed but not released yet

**Comment by wseagar** [comment]
v1.4 has been released which includes a fix for this. Can you give it a go now? @jaff80

**Comment by jaff80** [comment]
@wseagar I am unable to test it because @gonzoheadhuncho is somehow no longer in my notifications tab and I can not find anyone verified with Twitter Blue in my notifications tab

**Comment by wseagar** [comment]
> @wseagar I am unable to test it because @gonzoheadhuncho is somehow no longer in my notifications tab and I can not find anyone verified with Twitter Blue in my notifications tab

@noway do you want to like a tweet by @jaff80 ? 😆

**Comment by noway** [comment]
@jaff80 what's your twitter handle?

**Comment by jaff80** [comment]
@noway It is @jaff80_roblox Sorry for the late reply!

**Comment by jaff80** [comment]
@noway It's working! 
![eight dollars working](https://user-images.githubusercontent.com/113552154/203926736-a8179f89-9b84-435a-a4ea-05a9e1d20779.PNG)

**Comment by noway** [comment]
Sweet, closing.
