### ISSUE TITLE
[BUG] Extension breaks search

### ISSUE THREAD

**Issue by Cassolotl** [wseagar/eight-dollars#64]
**Info:**
 - Browser: Chrome
 - Platform: Mac
 - Extension Version: 1.5
 - Location: UK

**What happened**
1. Go to https://twitter.com/explore
2. Click cursor into search textbox
3. Search dropdown looks like this:
<img width="528" alt="Screenshot 2022-11-26 at 23 58 48" src="https://user-images.githubusercontent.com/6607512/204113418-6baffdbb-0723-47fc-9e80-0b4eb5e569c7.png">

4. Type a search term (e.g. `something`) and press enter, and you get this:
<img width="546" alt="Screenshot 2022-11-26 at 23 59 21" src="https://user-images.githubusercontent.com/6607512/204113436-9cdf7d9f-6cdd-4f65-82d4-fbe51a257055.png">

5. Press enter again and the search actually runs, but the results are this:
<img width="618" alt="Screenshot 2022-11-26 at 23 59 33" src="https://user-images.githubusercontent.com/6607512/204113451-f381214f-104a-4f03-aa54-abb973a5893a.png">

**Expected behavior**
1. Go to https://twitter.com/explore
2. Click cursor into search textbox
3. Search dropdown looks like this:
<img width="523" alt="Screenshot_2022-11-27_at_00_05_38" src="https://user-images.githubusercontent.com/6607512/204113494-fa2df40f-5d00-4339-885e-cc8671f3df71.png">

4. Press enter only once, and get results like this:
<img width="620" alt="Screenshot 2022-11-27 at 00 06 56" src="https://user-images.githubusercontent.com/6607512/204113516-2228e854-0688-4885-9dcc-1e87f33efe30.png">

**Additional context**
Can't think of anything.

**Comment by jerryasher** [comment]
Yes, I documented this in #63, but I don't even know why it is in this extension. It seems to be completely unrelated.

I would like an easier twitter advanced search ui than what they give us, but I don't think it should be here.

**Comment by noway** [comment]
The advanced search is now disabled by default in the `main` version of the extension - will be included in the next version.
