### ISSUE TITLE
Bug in spaces

### ISSUE THREAD

**Issue by TSyndrome** [wseagar/eight-dollars#7]
![image](https://user-images.githubusercontent.com/407935/201179743-856a5022-cd91-4471-92fc-3a778bf7a6dc.png)

Clips on the right side

**Comment by wseagar** [comment]
Have fixed this it will only show the smaller icon. Will go out with v1.2 tomorrow https://github.com/wseagar/eight-dollars/commit/36d76785ad23917f9ff7e81ac3a89fb1fd02280f . Thanks for reporting this!
